/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiLinkedinWithCircle: typeof import('~icons/bi/linkedin-with-circle')['default']
    IEntypoSocialLinkedinWithCircle: typeof import('~icons/entypo-social/linkedin-with-circle')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiKeyboardArrowLeft: typeof import('~icons/mdi/keyboard-arrow-left')['default']
    IMdiKeyboardArrowRight: typeof import('~icons/mdi/keyboard-arrow-right')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiLinkedIn: typeof import('~icons/mdi/linked-in')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
