/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    ILogosBootstrap: typeof import('~icons/logos/bootstrap')['default']
    ILogosGit: typeof import('~icons/logos/git')['default']
    ILogosGitIcon: typeof import('~icons/logos/git-icon')['default']
    ILogosGitlab: typeof import('~icons/logos/gitlab')['default']
    ILogosGitlabIcon: typeof import('~icons/logos/gitlab-icon')['default']
    ILogosGraphql: typeof import('~icons/logos/graphql')['default']
    ILogosJavascript: typeof import('~icons/logos/javascript')['default']
    ILogosLaravel: typeof import('~icons/logos/laravel')['default']
    ILogosMysql: typeof import('~icons/logos/mysql')['default']
    ILogosNuxtIcon: typeof import('~icons/logos/nuxt-icon')['default']
    ILogosPostgresql: typeof import('~icons/logos/postgresql')['default']
    ILogosSpring: typeof import('~icons/logos/spring')['default']
    ILogosSpringIcon: typeof import('~icons/logos/spring-icon')['default']
    ILogosTailwindcss: typeof import('~icons/logos/tailwindcss')['default']
    ILogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    ILogosTypescript: typeof import('~icons/logos/typescript')['default']
    ILogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    ILogosVuetify: typeof import('~icons/logos/vuetify')['default']
    ILogosVuetifyjs: typeof import('~icons/logos/vuetifyjs')['default']
    IMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    IMdiCloseThick: typeof import('~icons/mdi/close-thick')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiKeyboardArrowLeft: typeof import('~icons/mdi/keyboard-arrow-left')['default']
    IMdiKeyboardArrowRight: typeof import('~icons/mdi/keyboard-arrow-right')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiWhatsapp: typeof import('~icons/mdi/whatsapp')['default']
    IMitVue: typeof import('~icons/mi/t-vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBPopover: typeof import('bootstrap-vue-next/directives/BPopover')['vBPopover']
  }
}
